name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tiger-ff/action@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: mscloudd
          heroku_email: wangpf321123@gmail.com